// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Index_selection
List Index_selection(const NumericMatrix& A, double b);
RcppExport SEXP _MMdens_Index_selection(SEXP ASEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(Index_selection(A, b));
    return rcpp_result_gen;
END_RCPP
}
// compute_c0_cpp
NumericVector compute_c0_cpp(NumericVector dist, NumericVector Z_v, NumericVector e, double lambda, double b, double N_tau);
RcppExport SEXP _MMdens_compute_c0_cpp(SEXP distSEXP, SEXP Z_vSEXP, SEXP eSEXP, SEXP lambdaSEXP, SEXP bSEXP, SEXP N_tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z_v(Z_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type e(eSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type N_tau(N_tauSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_c0_cpp(dist, Z_v, e, lambda, b, N_tau));
    return rcpp_result_gen;
END_RCPP
}
// closest_index
int closest_index(NumericVector dist, double r);
RcppExport SEXP _MMdens_closest_index(SEXP distSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(closest_index(dist, r));
    return rcpp_result_gen;
END_RCPP
}
// hatc0_cpp
NumericVector hatc0_cpp(NumericVector dist, NumericVector r, NumericVector Z_v, NumericVector e, double lambda, double b, double N_tau);
RcppExport SEXP _MMdens_hatc0_cpp(SEXP distSEXP, SEXP rSEXP, SEXP Z_vSEXP, SEXP eSEXP, SEXP lambdaSEXP, SEXP bSEXP, SEXP N_tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dist(distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z_v(Z_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type e(eSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type N_tau(N_tauSEXP);
    rcpp_result_gen = Rcpp::wrap(hatc0_cpp(dist, r, Z_v, e, lambda, b, N_tau));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MMdens_Index_selection", (DL_FUNC) &_MMdens_Index_selection, 2},
    {"_MMdens_compute_c0_cpp", (DL_FUNC) &_MMdens_compute_c0_cpp, 6},
    {"_MMdens_closest_index", (DL_FUNC) &_MMdens_closest_index, 2},
    {"_MMdens_hatc0_cpp", (DL_FUNC) &_MMdens_hatc0_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_MMdens(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
