# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Index_selection <- function(A, b) {
    .Call(`_MMdens_Index_selection`, A, b)
}

compute_c0_cpp <- function(dist, Z_v, e, lambda, b, N_tau) {
    .Call(`_MMdens_compute_c0_cpp`, dist, Z_v, e, lambda, b, N_tau)
}

closest_index <- function(dist, r) {
    .Call(`_MMdens_closest_index`, dist, r)
}

hatc0_cpp <- function(dist, r, Z_v, e, lambda, b, N_tau) {
    .Call(`_MMdens_hatc0_cpp`, dist, r, Z_v, e, lambda, b, N_tau)
}

