# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

neighbors_matrix_condition <- function(A, b) {
    .Call('_SpatialCovariance_neighbors_matrix_condition', PACKAGE = 'SpatialCovariance', A, b)
}

